from abc import ABC, abstractmethod
from uuid import UUID

from app.domain.entities.user import User


class UserRepository(ABC):
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def get_by_id(self, user_id: UUID, tenant_id: str) -> User | None: ...
    @abstractmethod
    async def get_by_email(self, email: str, tenant_id: str) -> User | None: ...
    @abstractmethod
    async def get_by_username(self, username: str, tenant_id: str) -> User | None: ...
    @abstractmethod
    async def update(self, user: User) -> User: ...
    @abstractmethod
    async def delete(self, user_id: UUID, tenant_id: str) -> bool: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str, limit: int = 20, offset: int = 0) -> list[User]: ...
